### ISSUE TITLE
Kill the killer

### ISSUE THREAD

**Issue by Vitali8** [TwelveIterations/HardcoreRevival#10]
During the "clinical death", switching to chat, you can damage other entities (mobs and players) and kill them.
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-b163786
    SpongeForge: 1.12.2-2586-7.1.0-BETA-2868
    Minecraft Forge: 14.23.1.2607

**Comment by BlayTheNinth** [comment]
Does this happen without Sponge? If so, what are the steps to reproduce (since I'm not seeing any issue in my Forge-only test). If it only happens with Sponge, you should report it to them instead.
