### ISSUE TITLE
Downed players sometimes teleport to their spawnpoint

### ISSUE THREAD

**Issue by seasonedfish** [TwelveIterations/HardcoreRevival#13]
This has happened a few times to me and my friends - sometimes, after getting knocked down, I would teleport back to my spawnpoint with the debuffs of a person that had been rescued (half a heart, hunger). 

Running mod version 1.1.8.

**Comment by BlayTheNinth** [comment]
Is there any pattern to it? What other mods are installed? Anything in the log when this happens?

**Comment by seasonedfish** [comment]
I've noticed that it might be connected with downed players logging off and logging back in. As for the log, I haven't seen anything unusual but I'll check the next time it happens. 

Here's the modlist: https://pastebin.com/7zJNMsjb

**Comment by BlayTheNinth** [comment]
Tried around a bunch with logging out while rescueing, before being rescued, etc.. Still no luck in reproducing this issue.

**Comment by seasonedfish** [comment]
Hmm, strange. Were you on a server or a LAN world? It has only happened to me on servers. 

Also, the last time that it happened, I died in the Twilight Forest. Nothing showed up in the server log but it said "Your home bed was missing or obstructed" in the chat and I was teleported to a seemingly random location in the forest. 

Just in case, I should clarify that the teleporting happens **after** the downed player is rescued, not when the player is down. So basically, they were rescued but instead of getting up at the spot they were knocked down, they get up at their spawn. Sorry, I should have been more clear in my first post.
