### ISSUE TITLE
[feature] Option to remove timer 

### ISSUE THREAD

**Issue by winsrp** [TwelveIterations/HardcoreRevival#16]
I play with friends on hardcore but we cannot always play together, and sometimes someone dies while playing alone. Since in multiplayer the times keeps going, and sometimes your friends are just a mile away, putting a timer of 10 hours look weird and it is not even enough sometimes, so, could there be a config option to just leave the dead guy there waiting for revival instead of having a timer?

This actually makes hardcore more fun, and encourages team play.

If everyone dies... it's game over then!

**Comment by BlayTheNinth** [comment]
Implemented for Minecraft 1.14.x+
