### ISSUE TITLE
[1.14.3] Stacktrace and player unable to log back in after death on dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [TwelveIterations/HardcoreRevival#19]
https://gist.github.com/ProsperCraft/2329b8ed20225193e642ede0a5d2805b

![2019-07-02_19 43 45](https://user-images.githubusercontent.com/4427684/60557255-fefc8180-9d01-11e9-94cb-23fe21e09508.png)

HardcoreRevival_1.14.3-3.0.4

**Comment by ProsperCraft** [comment]
Message needs localizing as well.

**Comment by BlayTheNinth** [comment]
What kind of death? Did they respawn or get revived or are they still knocked out? It looks like all capabilities have been stripped from the player for some reason and both Overloaded and Mine and Slash do not guard against them missing.

What message needs localizing?

**Comment by ProsperCraft** [comment]
Just died, did not get revived. 

the message in the screenshot.  death.attack.not_rescued_in_time.player

**Comment by BlayTheNinth** [comment]
Fixing the localization issue, but the crashes are from incorrect `Optional` handling in Overloaded (where it has since been fixed at least on GitHub) and Mine and Slash.

**Comment by BlayTheNinth** [comment]
Closing now since I assume the mods got fixes and I think I remember a fix for something related to this going into Forge too.
