### ISSUE TITLE
"accept your fate" button does not work

### ISSUE THREAD

**Issue by colemy** [TwelveIterations/HardcoreRevival#20]
"accept your fate" button does nothing when clicked after it has gone from dark grey to light grey, player must press escape and hit the normal respawn button instead, please fix. using hardcore revival version 3.0.4 and forge version 1.14.4-28.0.24

**Comment by BlayTheNinth** [comment]
Forge made players no longer tick when they're at zero health, which Hardcore Revival obviously depended on. I've let them know and am hoping for a minor change there that should restore functionality before I waste time on a workaround.

**Comment by BlayTheNinth** [comment]
This has now been fixed in Forge. Update both Hardcore Revival and Forge.
