### ISSUE TITLE
crash when loading new world

### ISSUE THREAD

**Issue by colemy** [TwelveIterations/HardcoreRevival#23]
client crashes during generating new world with hardcore revival version 3.0.7 and forge 28.0.93

---- Minecraft Crash Report ----
// Why did you do that?

Time: 9/7/19 1:20 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at net.blay09.mods.hardcorerevival.handler.PlayerHandler.onPlayerLogin(PlayerHandler.java:32) ~[?:3.0.7] {}
	at net.minecraftforge.eventbus.ASMEventHandler_176_PlayerHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:43) ~[?:?] {}
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:205) ~[?:?] {}
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116) ~[?:?] {}
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63) ~[?:?] {}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224) ~[?:?] {}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 633430096 bytes (604 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar runtimedistcleaner PLUGINSERVICE 
		/optifine-f4-pre4-mod.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.0.93.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.93
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		AmbientSounds-3.0.9.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		AppleSkin-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		BetterSprinting-v3.0.1a.jar Better Sprinting {bettersprinting@3.0.1a DONE}
		BetterTitleScreen-1.14.4-1.7.jar Better Title Screen {bettertitlescreen@1.14.4-1.7 DONE}
		biomeinfo-1.14.4-v1.2.4.jar BiomeInfo {biomeinfo@v1.2.4 DONE}
		BiomesOPlenty-1.14.4-9.0.0.252-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.252 DONE}
		caelus-FORGE-1.14.4-0.11.jar Caelus API {caelus@FORGE-1.14.4-0.11 DONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 DONE}
		Controlling-5.0.3.jar Controlling {controlling@5.0.3 DONE}
		Craftable+Saddles+[1.14]-1.3.jar Craftable Saddles {craftable_saddles@1.3 DONE}
		craftingstation-2.0.2a.jar Crafting Station {craftingstation@2.0.2a DONE}
		curios-FORGE-1.14.4-0.24.jar Curios API {curios@FORGE-1.14.4-0.24 DONE}
		curiouselytra-FORGE-1.14.4-0.7.jar Curious Elytra {curiouselytra@FORGE-1.14.4-0.7 DONE}
		DefaultOptions-10.2.6.jar Default Options {defaultoptions@10.2.6 DONE}
		dragon-drops-elytra-1.14.4-1.0.jar Dragon Drops Elytra {dde@1.0 DONE}
		dwmh-1.14.4-3.0.1.jar Dude! Where's my Horse? {dwmh@1.14.4-3.0.1 DONE}
		elevator-1.5.1.jar Elevator Mod {elevatorid@1.14.4-1.5.1 DONE}
		extcaves-1.1.jar Extended Caves {extcaves@1.1 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		FleshToLeather-1.14.3-1.1.0.jar FleshToLeather {fleshtoleather@1.1.0 DONE}
		furniture-7.0.0-pre5.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre5 DONE}
		GamemodeOverhaul-1.14.4-1.4.2.1.jar GamemodeOverhaul {gamemodeoverhaul@1.14.4-1.4.2.1 DONE}
		HardcoreRevival_1.14.4-3.0.7.jar Hardcore Revival {hardcorerevival@3.0.7 DONE}
		Harvest-forge-1.2.10-23.jar Harvest {harvest@version DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		inventorysorter-1.14.4-15.2.0.jar Simple Inventory Sorter {inventorysorter@15.2.0 DONE}
		ironchest-9.0.4.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		jei-1.14.4-6.0.0.11.jar Just Enough Items {jei@6.0.0.11 DONE}
		KleeSlabs-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 DONE}
		lampblock-branders-v1.1.1-1.14.4.jar Lamp Block Mod {lampblockmod@1.1.1 DONE}
		LightOverlay-3.4.jar Light Overlay Forge {lightoverlay-forge@3.4 DONE}
		metalbarrels-1.3c.jar Metal Barrels {metalbarrels@1.3c DONE}
		mining_dimension-1.14.4-1.0.2.jar Mining World {mining_dimension@1.14.4-1.0.2 DONE}
		Morpheus-1.14.4-4.2.38.jar Morpheus {morpheus@version DONE}
		mountedpearl-1.14.4-0.0.1.jar Mounted Pearl Mod {mountedpearl@1.14.4-0.0.1 DONE}
		nat-charged-creepers-1.1.jar Naturally Charged Creepers {ncc@1.1 DONE}
		Ping-1.6.3.jar Ping {ping@1.14.4-1.6.3 DONE}
		Placebo-1.14.4-2.2.0.jar Placebo {placebo@2.2.0 DONE}
		practicaltools-1.4.jar Practical Tools {practicaltools@1.14.4-1.4 DONE}
		reap-1.10.1.jar Reap Mod {reap@1.10.1 DONE}
		ring-of-angel-1.0.1.jar Angel Ring {angelring@1.0.1 DONE}
		RingOfAttraction-1.14.4-1.0.10.jar Ring of Attraction {ring_of_attraction@1.0.10 DONE}
		RingOfBlink-1.14.4-1.0.13.jar Ring of Blink {ring_of_blink@1.0.13 DONE}
		RingOfEnderchest-1.14.4-1.0.10.jar Ring of Enderchest {ring_of_enderchest@1.0.10 DONE}
		RingOfMiner-1.14.4-1.0.8.jar Ring of Miner {ring_of_miner@1.0.8 DONE}
		RingOfRepair-1.14.4-1.0.11.jar Ring of Repair {ring_of_repair@1.0.11 DONE}
		ScreenshotToClipboard-1.14.3-1.0.2.jar Screenshot to Clipboard {screenshotclipboard@1.14.3-1.0.2 DONE}
		searchablechests-1.5.1.jar Searchable Chests {searchablechests@1.5.1 DONE}
		SimpleDivingGear-3.0.1.jar Simple Diving Gear {simpledivegear@3.0.1 mc 1.14.4 DONE}
		smooth-scrolling-everywhere-1.1.jar Smooth Scrolling Everywhere {smooth-scrolling-everywhere@1.1 DONE}
		spiketraps-1.0.jar Spike Traps {spiketraps@1.0 DONE}
		strongfarmland-1.14.4-1.0.0.jar Stronger Farmland Mod {strongfarmland@1.14.4-1.0.0 DONE}
		sulfur-potassium-branders-2.2.2-1.14.4.jar Sulfur And Potassium - make gunpowder {sulfurpotassiummod@2.2.2 DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		ToastControl-1.14.4-2.2.0.jar Toast Control {toastcontrol@2.2.0 DONE}
		tombstone-4.1.1-1.14.4.jar Corail Tombstone {tombstone@4.1.1 DONE}
		tramplestopper-2.0.0.22.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.22-universal DONE}
		TrashSlot-10.4.5.jar TrashSlot {trashslot@10.4.5 DONE}
		useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 DONE}
		useful_backpacks-u-team-core-1.14.4-2.5.5.120.jar U Team Core {uteamcore@2.5.5.120 DONE}
		voxel-map-1.9.13b.jar VoxelMap {voxelmap@1.9.13 DONE}
		Waddles-0.8.3.jar Waddles {waddles@1.14.4-0.8.3 DONE}
		well-fed-branders-1.14.4-1.2.0.jar Well Fed - quality food! {wellfedmod@1.2.0 DONE}
		worldedit-forge-7.0.1.jar WorldEdit {worldedit@7.0.1;61bc012 DONE}
		forge-1.14.4-28.0.93-universal.jar Forge {forge@28.0.93 DONE}
		forge-1.14.4-28.0.93-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['cpm9'/374, l='127 test', x=-230.50, y=81.00, z=205.50]]
	Data Packs: vanilla, mod:worldedit, mod:wellfedmod, mod:waila, mod:waddles, mod:voxelmap, mod:uteamcore, mod:usefulbackpacks, mod:trashslot, mod:tramplestopper, mod:tombstone, mod:toastcontrol, mod:swingthroughgrass, mod:sulfurpotassiummod, mod:strongfarmland, mod:spiketraps, mod:smooth-scrolling-everywhere, mod:simpledivegear, mod:searchablechests, mod:screenshotclipboard, mod:ring_of_repair, mod:ring_of_miner, mod:ring_of_enderchest, mod:ring_of_blink, mod:ring_of_attraction, mod:reap, mod:practicaltools, mod:placebo, mod:ping, mod:ncc, mod:mountedpearl, mod:morpheus, mod:mining_dimension, mod:metalbarrels, mod:lightoverlay-forge, mod:lampblockmod, mod:kleeslabs, mod:jei, mod:ironchest, mod:inventorysorter, mod:harvest, mod:hardcorerevival, mod:gamemodeoverhaul, mod:forge, mod:fleshtoleather, mod:fastleafdecay, mod:extcaves, mod:elevatorid, mod:dwmh, mod:defaultoptions, mod:dde, mod:curiouselytra, mod:curios, mod:craftingstation, mod:craftable_saddles, mod:controlling, mod:clumps, mod:cfm, mod:caelus, mod:biomesoplenty, mod:biomeinfo, mod:bettertitlescreen, mod:bettersprinting, mod:appleskin, mod:angelring, mod:ambientsounds
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by GamertechAU** [comment]
Getting the same crash and log on Forge .93-.101
