### ISSUE TITLE
reviving in the end dimension

### ISSUE THREAD

**Issue by colemy** [TwelveIterations/HardcoreRevival#28]
when reviving a player in the end dimension the revived player spawns into the overworld dimension

edit: hardcore revival version 3.0.10 and forge 28.1.96

**Comment by BlayTheNinth** [comment]
Yeah, `recreatePlayerEntity` is one big mess of a function and for some reason it looks like Forge is patching it so it'll overwrite the dimension passed in if the dimension claims respawns aren't allowed. Will have to see about a workaround.
