### ISSUE TITLE
corail tombstone compat

### ISSUE THREAD

**Issue by colemy** [TwelveIterations/HardcoreRevival#29]
When used with the corail tombstone mod the death message is bugged. Posting on both trackers because I don't know which mod is responsible.

Forge 28.1.96
Corail Tombstone 4.1.7
Hardcore Revival 3.0.10

> [Server thread/WARN] [tombstone/]: The death event of the player TextComponent{text='cpm9', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}} was cancelled by another mod
> 
> [Server thread/INFO] [minecraft/DedicatedServer]: death.attack.not_rescued_in_time

**Comment by BlayTheNinth** [comment]
Is it only showing it wrong in the log? Because that would be normal on dedicated servers, they do not load language files. The message in chat is showing fine for me.
