### ISSUE TITLE
[Mod Compatibility] JourneyMap doesn't create Death Point

### ISSUE THREAD

**Issue by Jomik** [TwelveIterations/HardcoreRevival#6]
JourneyMap is unable to intercept the respawn from HardcoreRevival it seems. As it doesn't create the death point when I press give up.

**Comment by techbrew-mc** [comment]
JM on the client can really only try to capture a deathpoint by detecting player.isDead on a client tick and then grabbing the player's final location.  Assuming you have the Create Deathpoints option enabled, my guess is something in HardcoreRevival is pre-empting that check?  Relevant code in JM is here:
https://gist.github.com/techbrew-mc/b4149b2d3f4a9398f5dffdae8c1a251f
